### ISSUE TITLE
Addon fails to load

### ISSUE THREAD

**Issue by Ashe** [migaku-official/Migaku-Anki-Addon#40]
Anki version: `Version 2.1.15 (442df9d6)`
Operating system: NixOS

So just following the basic Migaku/anki installation guide and hit a bit of a roadblock:

> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

```
When loading 'Migaku Anki Add-on':
Traceback (most recent call last):
File "/nix/store/mqbxii9lxv11y2cvm1jzvzbbf02fliw5-anki-2.1.15/lib/python3.9/site-packages/aqt/addons.py", line 80, in loadAddons
  __import__(dir)
File "/home/ashe/.local/share/Anki2/addons21/1846879528/__init__.py", line 38, in <module>
  from . import (
File "/home/ashe/.local/share/Anki2/addons21/1846879528/note_type_dialogs.py", line 10, in <module>
  from . import note_type_mgr
File "/home/ashe/.local/share/Anki2/addons21/1846879528/note_type_mgr.py", line 7, in <module>
  from anki.models import NotetypeDict
ImportError: cannot import name 'NotetypeDict' from 'anki.models' (/nix/store/mqbxii9lxv11y2cvm1jzvzbbf02fliw5-anki-2.1.15/lib/python3.9/site-packages/anki/models.py)
```

NixOS is a bit of a snowflake OS so don't worry too much about the details and the paths. However, if there's a file path which is typical and anki is assuming its location, then this could be a NixOS issue. Either way, some guidance on what could be going on would be greatly appreciated since I don't really know how else I'm going to start my journey if I'm shut down from the get-go!

**Comment by RicBent** [comment]
No worries, I know what NixOS is :)

The problem is that your Anki version is way outdated. The new Migaku Anki add-ons only work on 2.1.49 or later.
They shouldn't even install on that version using the Ankiweb codes. I guess you installed the .ankiaddon files directly? I guess I need to add a version check for those as well.

**Comment by Ashe** [comment]
I didn't realise! On this page https://ankiweb.net/shared/info/1846879528 at the top it said 'required 2.1' so I thought I was okay! I'm sorry. I REALLY appreciate how quickly you responded!

There's another package - `anki-bin`in nixpkgs and this one does indeed work!

Thanks to your impeccable response time that was solved near-instantly. Really appreciate this and I will remember how helpful you've been!
